### ISSUE TITLE
Manual tests don't work on 0.2.0

### ISSUE THREAD

**Issue by Reinmar** [benderjs/benderjs#161]
```
error: [middleware-tests]  TypeError: Object #<File> has no method 'then'
    at /www/benderjs/lib/pagebuilders/manual.js:35:7
    at tryCatchReject (/www/benderjs/node_modules/when/lib/makePromise.js:758:30)
    at runContinuation1 (/www/benderjs/node_modules/when/lib/makePromise.js:728:4)
    at Fulfilled.when (/www/benderjs/node_modules/when/lib/makePromise.js:544:4)
    at Pending.run (/www/benderjs/node_modules/when/lib/makePromise.js:438:13)
    at runQueue (/www/benderjs/node_modules/when/lib/Scheduler.js:75:18)
    at Scheduler._drain (/www/benderjs/node_modules/when/lib/Scheduler.js:50:3)
    at Scheduler.drain (/www/benderjs/node_modules/when/lib/Scheduler.js:26:9)
    at process._tickCallback (node.js:419:13)
```

**Comment by gregpabian** [comment]
Note to self: write the darn unit tests for the *pagebuilder/manual.js* and *middleware/manual.js* :angry:

**Comment by Reinmar** [comment]
The patch works. Can we get a new Bender release?

**Comment by gregpabian** [comment]
Well, if it's urgent then yes, I'll just have to move some of the items for this milestone to the next one.

**Comment by gregpabian** [comment]
Actually, I'd like to finish the UTs for this issue first. Could the release wait till tomorrow?

**Comment by Reinmar** [comment]
Yep. No problem.
