### ISSUE TITLE
Bender crashes when loading a file on the master branch.

### ISSUE THREAD

**Issue by Reinmar** [benderjs/benderjs#200]
On current master (57df1f3) when opening a manual test I have:

```
error: [middleware-tests]  TypeError: Object #<Object> has no method 'replace'
    at toArray (/www/ckeditor-dev/tests/_benderjs/ckeditor/lib/testbuilder.js:18:14)
    at /www/ckeditor-dev/tests/_benderjs/ckeditor/lib/testbuilder.js:29:27
    at Array.forEach (native)
    at /www/ckeditor-dev/tests/_benderjs/ckeditor/lib/testbuilder.js:28:32
    at Array.forEach (native)
    at build (/www/ckeditor-dev/tests/_benderjs/ckeditor/lib/testbuilder.js:21:28)
    at runTask (/www/benderjs/node_modules/when/pipeline.js:34:12)
    at /www/benderjs/node_modules/when/pipeline.js:42:12
    at /www/benderjs/node_modules/when/lib/decorators/array.js:234:14
    at tryCatchReject (/www/benderjs/node_modules/when/lib/makePromise.js:758:30)
```

**Comment by gregpabian** [comment]
It's a bug of the CKEditor plugin for Bender that relied on a "buggy" output of Bender's directive parser and a fix is already waiting [here](http://dev.ckeditor.com/ticket/13103).

**Comment by gregpabian** [comment]
Closed on CKEditor side.
